version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
      - SQLUSER=sa
    ports:
      - "1433:1433"
    networks:
      - mssql-network
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:

networks:
  mssql-network:
    driver: bridge